name: Lint Frontend Views

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-html:
    name: Lint HTML Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Tidy
        run: |
          sudo apt-get update
          sudo apt-get install -y tidy

      - name: Validate HTML
        run: find ./src/main/resources/templates -name "*.html" -exec tidy -errors -quiet {} + || [ $? -eq 1 ]

